### ISSUE TITLE
[Issue] Change inventory

### ISSUE THREAD

**Issue by AndreasFromDanmark** [Project-Sloth/ps-microphone#10]
I want to use it with qb-inventory, but i cant?

![image](https://user-images.githubusercontent.com/35656492/193636518-037dee6c-f4bf-495a-b314-a494c970fa5f.png)
![image](https://user-images.githubusercontent.com/35656492/193636632-164f295c-98d4-4778-b2b9-38acc8b6ede1.png)

**Comment by OGPandaYT** [comment]
Try: QBCore.Functions.CreateUseableItem("megaphone", function(source,item)
    TriggerClientEvent("megaphone:Toggle",source)
end)
