### ISSUE TITLE
Issue with PMA-VOICE - Microphone overide not doing anything.

### ISSUE THREAD

**Issue by Rhodinium** [Project-Sloth/ps-microphone#13]
Using latest pma-voice.

No matter what I try the pma export to overide doesnt seem to work.

The hud updates as it should, the items work as should, it's triggering the functions etc but the voip distance is not effected, Seems there are many with this issue.

Any ideas?

**Comment by theMani-kh** [comment]
Effect (submix) isn't working, just update distance.

**Comment by MonkeyWhisper** [comment]
Working, just tested.

**Comment by suryabhaiin** [comment]
Use latest pma-voice
